# Generated by Django 5.2.3 on 2025-06-28 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currentbalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currentbalance", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TrackingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "expensestype",
                    models.CharField(
                        max_length=200,
                        verbose_name=(("CREDIT", "CREDIT"), ("DEBIT", "DEBIT")),
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("created_by", models.DateTimeField(auto_now=True)),
                ("updated_by", models.DateTimeField(auto_now_add=True)),
                (
                    "currentbalance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.currentbalance",
                    ),
                ),
            ],
        ),
    ]
