# Generated by Django 5.2.3 on 2025-06-28 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trackinghistory",
            old_name="updated_by",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="trackinghistory",
            name="created_by",
        ),
    ]
